package protoflex

import chisel3._
import chisel3.iotesters
import chisel3.iotesters.{ChiselFlatSpec, Driver, PeekPokeTester}

import utils.AssemblyParser
import utils.AssemblyInstruction
import utils.DInstExtractor
import common.DEC_LITS._

class ProcTestsPipeline(c: Proc) extends PeekPokeTester(c)
{
  val random = scala.util.Random
  def printState() = {
    val sFet = peek(c.io.inst_in)
    val sDec = if(peek(c.io.dec_reg.valid) == 1) peek(c.io.dec_reg) else "Invalid"
    val sIss = if(peek(c.io.issue_reg.valid) == 1) peek(c.io.issue_reg) else "Invalid"
    val sExe = if(peek(c.io.exe_reg.valid) == 1) peek(c.io.exe_reg) else "Invalid"
    val sBr = if(peek(c.io.br_reg.valid) == 1) peek(c.io.br_reg) else "Invalid"
    val wbEn =  peek(c.io.wen)
    val state = Seq(
      "____________________________________________________________________________________",
      "Inst in : " + sFet,
      " | ",
      " | ",
      "------ DECODE STAGE ------",
      " | ",
      "Reg_Dec : " + sDec,
      " | ",
      " | ",
      "------ ISSUE STAGE ------",
      " | ",
      "Reg_Iss : " + sIss,
      " | ",
      "------ EXECUTE STAGE ------",
      " | ",
      " |------------|",
      " |            |",
      "Reg_Exe : " + sExe,
      " |            |",
      " |           Reg_Br : " + sBr,
      " |            |",
      " |------------|",
      " | ",
      "------ WB STAGE ------",
      " | ",
      " PC : " + peek(c.io.curr_PC) + " -> " + peek(c.io.next_PC) + " || WB : " + wbEn,
      "____________________________________________________________________________________"
    )
    state map (println(_))
  }
  val insts = AssemblyParser.parse("alu.x")
  val br_insts = AssemblyParser.parse("branch.x")
  poke(c.io.br_reg.ready, 1)
  poke(c.io.exe_reg.ready, 1)
  for(i <- 0 until 20) {
    printState()
    val itype = random.nextInt(2)
    val inst = if (itype == 0) insts(random.nextInt(insts.size)) else br_insts(random.nextInt(br_insts.size))
    poke(c.io.inst, inst.bitPat)
    poke(c.io.tag, random.nextInt(4))
    poke(c.io.valid, 1)
    step(1)
  }

}

class ProcTester extends ChiselFlatSpec
{
  behavior of "Proc"

  backends foreach { backend =>
    "ProcTestsReadyValid" should s"test Proc pipeline (with $backend)" in {
      Driver(() => new Proc, backend)((c) => new ProcTestsPipeline(c)) should be (true)
    }
  }
}

/**
  * This provides a way to ruin the firrtl-interpreter REPL (or shell)
  * on the lowered firrtl generated by your circuit. You will be placed
  * in an interactive shell. This can be very helpful as a debugging
  * technique. Type help to see a list of commands.
  */
