name: Scala CI

on:
  push:
   branches: 
      - master
      - dev
      - switch_to_mill
  pull_request:
    branches: [ master ]

jobs:
  scala_unit_test:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v2
    - uses: jodersky/setup-mill@master
      with:
        mill-version: 0.10.5
    - name: Setup Verilator
      run: sudo apt update && sudo apt install verilator -y && verilator --version
    - name: Run tests
      run: mill Devteroflex.test
  cpp_unit_test:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v2
    - uses: jodersky/setup-mill@master
      with:
        mill-version: 0.10.5
    - name: Setup Verilator
      run: sudo apt update && sudo apt install verilator -y && verilator --version
    - name: Generate Verilog
      run: mill Devteroflex.exportVerilog
    - name: Build Simulator
      working-directory: ./regression
      run: mkdir build && cd build && cmake .. -G "Unix Makefiles" && make -j
    - name: Run every unit test
      working-directory: ./regression
      run: ./runAll.sh
