name: Scala CI

on:
  push:
   branches: 
      - master
      - dev
      - automatic_unit_test
  pull_request:
    branches: [ master ]

jobs:
  scala_unit_test:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Setup Verilator
      run: sudo apt update && sudo apt install verilator -y && verilator --version
    - name: Run tests
      run: sbt test
  cpp_unit_test:
    runs-on: ubuntu-20.04
    needs: scala_unit_test
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Setup Verilator
      run: sudo apt update && sudo apt install verilator -y && verilator --version
    - name: Generate Verilog
      run: sbt "runMain ARMFlexTopSimulatorVerilogEmitter"
    - name: Run CMake
      run: cd regression && mkdir build && cd build && cmake .. -G "Unix Makefiles"
    - name: Run Make
      run: make -j
    - name: Run every unit test
      run: cd .. && ./runAll.sh
